{
 "title": "Kubernetes Monitoring K8sCluster",
 "tags": [
  "k8s",
  "monitoring",
  "L1"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "alertmanager",
    "label": "Alertmanager",
    "query": "camptocamp-prometheus-alertmanager-datasource"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info, cluster)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_exporter_build_info{cluster=\"$cluster\", pod!~\"virt-launcher.*|\"}, job)"
    }
   },
   {
    "name": "masterInstance",
    "label": "Master Instance",
    "query": {
     "query": "label_values(master_uname_info{cluster=\"$cluster\"}, instance)"
    }
   },
   {
    "name": "workerInstance",
    "label": "Worker Instance",
    "query": {
     "query": "label_values(worker_uname_info{cluster=\"$cluster\"}, instance)"
    }
   },
   { "name": "datasource_logs", "label": "Logs datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{cluster=\"$cluster\", alertname!=\"Watchdog\", alertstate=~\"firing|pending\", severity=\"critical\", alertgroup=~\"Cluster|ClusterApp\"}) OR on() vector(0)",
     "type": "single"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{cluster=\"$cluster\", alertname!=\"Watchdog\", alertstate=~\"firing|pending\", severity=\"warning\", alertgroup=~\"Cluster|ClusterApp\"}) OR on() vector(0)",
     "type": "single"
    }
   ]
  },
  {
   "title": "Control Plane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API Server",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _apiServerHealth_",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(up{cluster=\"$cluster\", job=\"apiserver\"}) / count(up{cluster=\"$cluster\", job=\"apiserver\"})) * 100 OR on() vector(-1)"
    }
   ]
  },
  {
   "title": "Controller Manager",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _controllerManagerHealth_",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(up{cluster=\"$cluster\", job=\"kube-controller-manager\"}) / count(up{cluster=\"$cluster\", job=\"kube-controller-manager\"})) * 100 OR on() vector(-1)"
    }
   ]
  },
  {
   "title": "Etcd",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _etcdHealth_",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(up{cluster=\"$cluster\", job=\"kube-etcd\"}) / count(up{cluster=\"$cluster\", job=\"kube-etcd\"})) * 100 OR on() vector(-1)"
    }
   ]
  },
  {
   "title": "Kubelet",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _kubeletHealth_",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(up{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\"}) / count(up{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\"})) * 100 OR on() vector(-1)"
    }
   ]
  },
  {
   "title": "Proxy",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _proxyHealth_",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(up{cluster=\"$cluster\", job=\"kube-proxy\"}) / count(up{cluster=\"$cluster\", job=\"kube-proxy\"})) * 100 OR on() vector(-1)"
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _schedulerHealth_",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(up{cluster=\"$cluster\", job=\"kube-scheduler\"}) / count(up{cluster=\"$cluster\", job=\"kube-scheduler\"})) * 100 OR on() vector(-1)"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes Health",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _nodeHealth_",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(kube_node_info{cluster=\"$cluster\"}) / (sum(kube_node_info{cluster=\"$cluster\"}) + sum(kube_node_spec_unschedulable{cluster=\"$cluster\"}) + sum(kube_node_status_condition{cluster=\"$cluster\", condition=~\"DiskPressure|MemoryPressure|PIDPressure\", status=~\"true|unknown\"})  + sum(kube_node_status_condition{cluster=\"$cluster\", condition=\"Ready\", status=~\"false|unknown\"}) ) * 100)"
    }
   ]
  },
  {
   "title": "Running StatefulSets",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _runningStatefulSets_",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(kube_statefulset_status_replicas_ready{cluster=\"$cluster\"}) / sum(kube_statefulset_status_replicas{cluster=\"$cluster\"}) * 100)"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _runningPods_",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(kube_pod_status_phase{cluster=\"$cluster\", phase=\"Running\"}) / (sum(kube_pod_status_phase{cluster=\"$cluster\", phase=\"Running\"}) + sum(kube_pod_status_phase{cluster=\"$cluster\", phase=\"Pending\"}) + sum(kube_pod_status_phase{cluster=\"$cluster\", phase=\"Failed\"}) + sum(kube_pod_status_phase{cluster=\"$cluster\", phase=\"Unknown\"})) * 100)"
    }
   ]
  },
  {
   "title": "Succeeded Jobs",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _succeededJobs_",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(kube_job_status_succeeded{cluster=\"$cluster\"}) / (sum(kube_job_status_succeeded{cluster=\"$cluster\"}) + sum(kube_job_status_failed{cluster=\"$cluster\"})) * 100) OR on() vector(-1)"
    }
   ]
  },
  {
   "title": "Deployments Health",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _deploymentsHealth_",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round((sum(kube_deployment_status_replicas_updated{cluster=\"$cluster\"}) + sum(kube_deployment_status_replicas_available{cluster=\"$cluster\"})) / (2 * sum(kube_deployment_status_replicas{cluster=\"$cluster\"})) * 100)"
    }
   ]
  },
  {
   "title": "DaemonSets Health",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _daemonSetsHealth_",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round((sum(kube_daemonset_status_updated_number_scheduled{cluster=\"$cluster\"} OR kube_daemonset_updated_number_scheduled{cluster=\"$cluster\"}) + sum(kube_daemonset_status_number_available{cluster=\"$cluster\"})) / (2 * sum(kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\"})) * 100)"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _runningContainers_",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(kube_pod_container_status_running{cluster=\"$cluster\"}) / (sum(kube_pod_container_status_running{cluster=\"$cluster\"}) + (sum(kube_pod_container_status_terminated_reason{cluster=\"$cluster\", reason!=\"Completed\"}) OR vector(0)) + sum(kube_pod_container_status_waiting{cluster=\"$cluster\"})) * 100)"
    }
   ]
  },
  {
   "title": "PVC Bound",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _pvcBound_",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(kube_persistentvolumeclaim_status_phase{cluster=\"$cluster\", phase=\"Bound\"}) / (\nsum(kube_persistentvolumeclaim_status_phase{cluster=\"$cluster\", phase=\"Bound\"}) + sum(kube_persistentvolumeclaim_status_phase{cluster=\"$cluster\", phase=\"Pending\"}) +\nsum(kube_persistentvolumeclaim_status_phase{cluster=\"$cluster\", phase=\"Lost\"})\n) * 100) OR on() vector(-1)"
    }
   ]
  },
  {
   "title": "Most Utilized PVC",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _mostUtilizedPVC_",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sum(((kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\"} - kubelet_volume_stats_available_bytes{cluster=\"$cluster\"}) / kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\"}) * 100) by (persistentvolumeclaim)) OR on() vector(-1)"
    }
   ]
  },
  {
   "title": "Master Nodes Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RAM",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall Utilization",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _overallUtilizationMasterNodesCPU_",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(round((1 - (avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"idle\"}[5m]) * on(instance, pod) group_left(nodename) (master_uname_info)) by (job, nodename) )) * 100))"
    }
   ]
  },
  {
   "title": "Most Utilized Node",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _mostUtilizedMasterNodeCPU_",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(round((1 - (avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"idle\"}[5m]) * on(instance, pod) group_left(nodename) (master_uname_info)) by (job, nodename) )) * 100))"
    }
   ]
  },
  {
   "title": "Overall Utilization",
   "type": "stat",
   "description": "The percentage of the memory utilization is calculated by:\n```\n1 - (<memory available>/<memory total>)\n```\n\nK8s monitoring template: _overallUtilizationMasterNodesRAM_",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(round((1 - sum by (job, nodename) (node_memory_MemAvailable_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info)) / sum by (job, nodename) (node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info))) * 100))"
    }
   ]
  },
  {
   "title": "Most Utilized Node",
   "type": "stat",
   "description": "The percentage of the memory utilization is calculated by:\n```\n1 - (<memory available>/<memory total>)\n```\n\nK8s monitoring template: _mostUtilizedMasterNodeRAM_",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(round((1 - sum by (job, nodename) (node_memory_MemAvailable_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info)) / sum by (job, nodename) (node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info))) * 100))"
    }
   ]
  },
  {
   "title": "Overall Utilization",
   "type": "stat",
   "description": "The percentage of the disk utilization is calculated using the fraction:\n```\n<space used>/(<space used> + <space free>)\n```\nThe value of <space free> is reduced by  5% of the available disk capacity, because   \nthe file system marks 5% of the available disk capacity as reserved. \nIf less than 5% is free, using the remaining reserved space requires root privileges.\nAny non-privileged users and processes are unable to write new data to the partition. See the list of explicitly ignored mount points and file systems [here](https://github.com/dNationCloud/kubernetes-monitoring-stack/blob/main/chart/values.yaml)\n\nK8s monitoring template: _overallUtilizationMasterNodesDisk_",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(round((sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info)) by (job, nodename, device) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info)) by (job, nodename, device)) / ((sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info)) by (job, nodename, device) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info)) by (job, nodename, device)) + sum(node_filesystem_avail_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info)) by (job, nodename, device)) * 100 > 0))"
    }
   ]
  },
  {
   "title": "Most Utilized Node",
   "type": "stat",
   "description": "The percentage of the disk utilization is calculated using the fraction:\n```\n<space used>/(<space used> + <space free>)\n```\nThe value of <space free> is reduced by  5% of the available disk capacity, because   \nthe file system marks 5% of the available disk capacity as reserved. \nIf less than 5% is free, using the remaining reserved space requires root privileges.\nAny non-privileged users and processes are unable to write new data to the partition. See the list of explicitly ignored mount points and file systems [here](https://github.com/dNationCloud/kubernetes-monitoring-stack/blob/main/chart/values.yaml)\n\nK8s monitoring template: _mostUtilizedMasterNodeDisk_",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(round((sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info)) by (job, nodename, device) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info)) by (job, nodename, device)) / ((sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info)) by (job, nodename, device) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info)) by (job, nodename, device)) + sum(node_filesystem_avail_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (master_uname_info)) by (job, nodename, device)) * 100))"
    }
   ]
  },
  {
   "title": "Overall Errors",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _overallMasterNodesNetworkErrors_",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(rate(node_network_transmit_errs_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"} [5m]) * on(instance, pod) group_left(nodename) (master_uname_info) ) by (job, nodename) + sum(rate(node_network_receive_errs_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m]) * on(instance, pod) group_left(nodename) (master_uname_info) ) by (job, nodename))"
    }
   ]
  },
  {
   "title": "Most Affected Node",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _mostUtilizedMasterNodeNetworkErrors_",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sum(rate(node_network_transmit_errs_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"} [5m]) * on(instance, pod) group_left(nodename) (master_uname_info) ) by (job, nodename) + sum(rate(node_network_receive_errs_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m]) * on(instance, pod) group_left(nodename) (master_uname_info) ) by (job, nodename))"
    }
   ]
  },
  {
   "title": "Used Cores",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _usedCoresMasterNodes_",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - (avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"idle\", instance=~\"$masterInstance\"}[5m])))) * count(node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"system\", instance=~\"$masterInstance\"})"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _totalCoresMasterNodes_",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"system\", instance=~\"$masterInstance\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _usedRAMMasterNodes_",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$masterInstance\"}) * (((1 - sum(node_memory_MemAvailable_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$masterInstance\"}) / sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$masterInstance\"}))))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _totalRAMMasterNodes_",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$masterInstance\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _usedDiskMasterNodes_",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$masterInstance\"}) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$masterInstance\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _totalDiskMasterNodes_",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$masterInstance\"})"
    }
   ]
  },
  {
   "title": "Worker Nodes Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RAM",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 12, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall Utilization",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _overallUtilizationWorkerNodesCPU_",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(round((1 - (avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"idle\"}[5m]) * on(instance, pod) group_left(nodename) (worker_uname_info)) by (job, nodename) )) * 100))"
    }
   ]
  },
  {
   "title": "Most Utilized Node",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _mostUtilizedWorkerNodeCPU_",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(round((1 - (avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"idle\"}[5m]) * on(instance, pod) group_left(nodename) (worker_uname_info)) by (job, nodename) )) * 100))"
    }
   ]
  },
  {
   "title": "Overall Utilization",
   "type": "stat",
   "description": "The percentage of the memory utilization is calculated by:\n```\n1 - (<memory available>/<memory total>)\n```\n\nK8s monitoring template: _overallUtilizationWorkerNodesRAM_",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(round((1 - sum by (job, nodename) (node_memory_MemAvailable_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info)) / sum by (job, nodename) (node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info))) * 100))"
    }
   ]
  },
  {
   "title": "Most Utilized Node",
   "type": "stat",
   "description": "The percentage of the memory utilization is calculated by:\n```\n1 - (<memory available>/<memory total>)\n```\n\nK8s monitoring template: _mostUtilizedWorkerNodeRAM_",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(round((1 - sum by (job, nodename) (node_memory_MemAvailable_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info)) / sum by (job, nodename) (node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info))) * 100))"
    }
   ]
  },
  {
   "title": "Overall Utilization",
   "type": "stat",
   "description": "The percentage of the disk utilization is calculated using the fraction:\n```\n<space used>/(<space used> + <space free>)\n```\nThe value of <space free> is reduced by  5% of the available disk capacity, because   \nthe file system marks 5% of the available disk capacity as reserved. \nIf less than 5% is free, using the remaining reserved space requires root privileges.\nAny non-privileged users and processes are unable to write new data to the partition. See the list of explicitly ignored mount points and file systems [here](https://github.com/dNationCloud/kubernetes-monitoring-stack/blob/main/chart/values.yaml)\n\nK8s monitoring template: _overallUtilizationWorkerNodesDisk_",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(round((sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info)) by (job, nodename, device) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info)) by (job, nodename, device)) / ((sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info)) by (job, nodename, device) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info)) by (job, nodename, device)) + sum(node_filesystem_avail_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info)) by (job, nodename, device)) * 100 > 0))"
    }
   ]
  },
  {
   "title": "Most Utilized Node",
   "type": "stat",
   "description": "The percentage of the disk utilization is calculated using the fraction:\n```\n<space used>/(<space used> + <space free>)\n```\nThe value of <space free> is reduced by  5% of the available disk capacity, because   \nthe file system marks 5% of the available disk capacity as reserved. \nIf less than 5% is free, using the remaining reserved space requires root privileges.\nAny non-privileged users and processes are unable to write new data to the partition. See the list of explicitly ignored mount points and file systems [here](https://github.com/dNationCloud/kubernetes-monitoring-stack/blob/main/chart/values.yaml)\n\nK8s monitoring template: _mostUtilizedWorkerNodeDisk_",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(round((sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info)) by (job, nodename, device) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info)) by (job, nodename, device)) / ((sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info)) by (job, nodename, device) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info)) by (job, nodename, device)) + sum(node_filesystem_avail_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance, pod) group_left(nodename) (worker_uname_info)) by (job, nodename, device)) * 100))"
    }
   ]
  },
  {
   "title": "Overall Errors",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _overallWorkerNodesNetworkErrors_",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(rate(node_network_transmit_errs_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"} [5m]) * on(instance, pod) group_left(nodename) (worker_uname_info) ) by (job, nodename) + sum(rate(node_network_receive_errs_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m]) * on(instance, pod) group_left(nodename) (worker_uname_info) ) by (job, nodename))"
    }
   ]
  },
  {
   "title": "Most Affected Node",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _mostUtilizedWorkerNodeNetworkErrors_",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sum(rate(node_network_transmit_errs_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"} [5m]) * on(instance, pod) group_left(nodename) (worker_uname_info) ) by (job, nodename) + sum(rate(node_network_receive_errs_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m]) * on(instance, pod) group_left(nodename) (worker_uname_info) ) by (job, nodename))"
    }
   ]
  },
  {
   "title": "Used Cores",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _usedCoresWorkerNodes_",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - (avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"idle\", instance=~\"$workerInstance\"}[5m])))) * count(node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"system\", instance=~\"$workerInstance\"})"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _totalCoresWorkerNodes_",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"system\", instance=~\"$workerInstance\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _usedRAMWorkerNodes_",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$workerInstance\"}) * (((1 - sum(node_memory_MemAvailable_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$workerInstance\"}) / sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$workerInstance\"}))))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _totalRAMWorkerNodes_",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$workerInstance\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _usedDiskWorkerNodes_",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$workerInstance\"}) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$workerInstance\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "\n\nK8s monitoring template: _totalDiskWorkerNodes_",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\", instance=~\"$workerInstance\"})"
    }
   ]
  }
 ]
}