{
 "title": "Loki Distributed",
 "tags": [
  "k8s",
  "app",
  "L1"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_uname_info, cluster)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(loki_build_info{cluster=\"$cluster\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_build_info{cluster=\"$cluster\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Log Messages Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(log_messages_total{cluster=\"$cluster\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(log_messages_total{cluster=\"$cluster\", job=~\"$job\",level=\"error\"})"
    }
   ]
  },
  {
   "title": "Panic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_panic_total{cluster=\"$cluster\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Messages Input",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Messages Input",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(log_messages_total{cluster=\"$cluster\", job=~\"$job\"}[1m])) by (level)",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "API Request Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket{cluster=\"$cluster\", job=~\"$job\"}[5m])) by (le,route))",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Request Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate( loki_request_message_bytes_bucket {cluster=\"$cluster\", job=~\"$job\"}[1m])) by (le,route))",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Response Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate( loki_response_message_bytes_bucket {cluster=\"$cluster\", job=~\"$job\"}[1m])) by (le,route))",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cache Value Size bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_cache_value_size_bytes_bucket{cluster=\"$cluster\", job=~\"$job\"}[5m])) by (le,name,method))",
       "legendFormat": "{{name}} / {{method}}"
      }
     ]
    },
    {
     "title": "Fetched Keys",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "loki_cache_fetched_keys{cluster=\"$cluster\", job=~\"$job\"}",
       "legendFormat": "{{container}}/{{name}}"
      }
     ]
    },
    {
     "title": "Hits Keys",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(loki_cache_hits{cluster=\"$cluster\", job=~\"$job\"}[5m])",
       "legendFormat": "{{container}}/{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Querier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cache Hits",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "loki_querier_index_cache_hits_total{cluster=\"$cluster\", job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "Cache Puts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "loki_querier_index_cache_puts_total{cluster=\"$cluster\", job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "Cache Gets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "loki_querier_index_cache_gets_total{cluster=\"$cluster\", job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "Cache Corruptions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "loki_querier_index_cache_corruptions_total{cluster=\"$cluster\", job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "Cache Encode Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "loki_querier_index_cache_encode_errors_total{cluster=\"$cluster\", job=~\"$job\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Blocks / Chunk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate( loki_ingester_blocks_per_chunk_bucket {cluster=\"$cluster\", job=~\"$job\"}[1m])) by (le))",
       "legendFormat": "blocks"
      }
     ]
    },
    {
     "title": "Chunk Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate( loki_ingester_chunk_size_bytes_bucket {cluster=\"$cluster\", job=~\"$job\"}[1m])) by (le))",
       "legendFormat": "chunk size"
      }
     ]
    },
    {
     "title": "Chunk Age",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate( loki_ingester_chunk_age_seconds_bucket {cluster=\"$cluster\", job=~\"$job\"}[1m])) by (le))",
       "legendFormat": "ages"
      }
     ]
    },
    {
     "title": "Chunk Compression Ratios",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate( loki_ingester_chunk_compression_ratio_bucket {cluster=\"$cluster\", job=~\"$job\"}[1m])) by (le))",
       "legendFormat": "ratio"
      }
     ]
    },
    {
     "title": "Chunk Encode Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate( loki_ingester_chunk_encode_time_seconds_bucket {cluster=\"$cluster\", job=~\"$job\"}[1m])) by (le))",
       "legendFormat": "time"
      }
     ]
    },
    {
     "title": "Lines / Chunk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate( loki_ingester_chunk_entries_bucket {cluster=\"$cluster\", job=~\"$job\"}[1m])) by (le))",
       "legendFormat": "lines"
      }
     ]
    }
   ]
  }
 ]
}