{
 "title": "Node Exporter-vishalk17",
 "tags": [
  "k8s",
  "nodeexporter",
  "L3"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_uname_info, cluster)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info{cluster=\"$cluster\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{cluster=\"$cluster\", job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "diskfs",
    "label": "Disk FileSystems",
    "query": "ext2,ext3,ext4,btrfs,vfat,fuseblk,jfs,zfs,reiserfs,f2fs,xfs"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{cluster=\"$cluster\", job=~\"$job\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round((1 - (avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"idle\"}[5m]) * on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))))) * 100)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "description": "The percentage of the memory utilization is calculated by:\n```\n1 - (<memory available>/<memory total>)\n```",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round((1 - (sum(node_memory_MemAvailable_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))) / sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\"}* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))) )) * 100)"
    }
   ]
  },
  {
   "title": "Most Utilized Disk",
   "type": "gauge",
   "description": "The percentage of the disk utilization is calculated using the fraction:\n```\n<space used>/(<space used> + <space free>)\n```\nThe value of <space free> is reduced by  5% of the available disk capacity, because   \nthe file system marks 5% of the available disk capacity as reserved. \nIf less than 5% is free, using the remaining reserved space requires root privileges.\nAny non-privileged users and processes are unable to write new data to the partition. See the list of explicitly ignored mount points and file systems [here](https://github.com/dNationCloud/kubernetes-monitoring-stack/blob/main/chart/values.yaml)",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(\nmax(\n(sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\"}) by (instance, device) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\"}) by (instance, device)) /\n(sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\"}) by (instance, device) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\"}) by (instance, device) +\nsum(node_filesystem_avail_bytes{cluster=\"$cluster\", job=~\"$job\"}) by (instance, device))\n * 100 \n * on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))\n)\n)"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_errs_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m]) * on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))) + \nsum(rate(node_network_receive_errs_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m]) * on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"system\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))"
    }
   ]
  },
  {
   "title": "Table of IP Addresses",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(_1_instance, _0_nodename) (\nlabel_replace(\nlabel_replace(\n  node_uname_info{cluster=\"$cluster\", job=~\"$job\", nodename=~\"$instance\"}\n    , \"_1_instance\", \"$1\", \"instance\", \"(.*):.*\")\n    , \"_0_nodename\",\"$1\", \"nodename\", \"(.*)\")\n)"
    }
   ]
  },
  {
   "title": "CPU Utilization / Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "round((1 - (avg by (nodename) (irate(node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"idle\"}[5m])\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))))) * 100)",
     "legendFormat": "cpu  - {{nodename}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (nodename) (node_load1{cluster=\"$cluster\", job=~\"$job\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))",
     "legendFormat": "1m load average {{nodename}}"
    },
    {
     "expr": "sum by (nodename) (node_load5{cluster=\"$cluster\", job=~\"$job\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))",
     "legendFormat": "5m load average {{nodename}}"
    },
    {
     "expr": "sum by (nodename) (node_load15{cluster=\"$cluster\", job=~\"$job\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))",
     "legendFormat": "15m load average {{nodename}}"
    },
    {
     "expr": "count by (nodename) (node_cpu_seconds_total{cluster=\"$cluster\", job=~\"$job\", mode=\"idle\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))",
     "legendFormat": "logical cores {{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "description": "The used memory is calculated by:\n```\n<memory total> - <memory available>\n```",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (nodename) (node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\"}* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))) - sum by (nodename) (node_memory_MemAvailable_bytes{cluster=\"$cluster\", job=~\"$job\"} * on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))",
     "legendFormat": "memory used - {{nodename}}"
    },
    {
     "expr": "sum by (nodename) (node_memory_MemAvailable_bytes{cluster=\"$cluster\", job=~\"$job\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))",
     "legendFormat": "memory available - {{nodename}}"
    },
    {
     "expr": "sum by (nodename) (node_memory_Buffers_bytes{cluster=\"$cluster\", job=~\"$job\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))",
     "legendFormat": "memory buffers - {{nodename}}"
    },
    {
     "expr": "sum by (nodename) (node_memory_Cached_bytes{cluster=\"$cluster\", job=~\"$job\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))",
     "legendFormat": "memory cached - {{nodename}}"
    },
    {
     "expr": "sum by (nodename) (node_memory_MemFree_bytes{cluster=\"$cluster\", job=~\"$job\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))",
     "legendFormat": "memory free - {{nodename}}"
    },
    {
     "expr": "sum by (nodename) (node_memory_MemTotal_bytes{cluster=\"$cluster\", job=~\"$job\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))",
     "legendFormat": "memory total - {{nodename}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk Utilization",
     "type": "graph",
     "description": "The percentage of the disk utilization is calculated using the fraction:\n```\n<space used>/(<space used> + <space free>)\n```\nThe value of <space free> is reduced by  5% of the available disk capacity, because   \nthe file system marks 5% of the available disk capacity as reserved. \nIf less than 5% is free, using the remaining reserved space requires root privileges.\nAny non-privileged users and processes are unable to write new data to the partition. See the list of types of displayed disk filesystems [here](https://github.com/dNationCloud/kubernetes-monitoring/blob/main/jsonnet/dashboards/grafana-templates.libsonnet) and list of explicitly ignored mount points and file systems at node-exporter level [here](https://github.com/dNationCloud/kubernetes-monitoring-stack/blob/main/chart/values.yaml)",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\", fstype=~\"$diskfs\"} * on(instance) group_left(nodename) (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))) by (device, instance, nodename, mountpoint)  - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\", fstype=~\"$diskfs\"} * on(instance) group_left(nodename) (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))) by (device, instance, nodename, mountpoint)",
       "legendFormat": "disk used {{device}} {{nodename}} {{mountpoint}}"
      },
      {
       "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\", fstype=~\"$diskfs\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))) by (device, instance, nodename, mountpoint)",
       "legendFormat": "disk size {{device}} {{nodename}} {{mountpoint}}"
      },
      {
       "expr": "sum(node_filesystem_avail_bytes{cluster=\"$cluster\", job=~\"$job\", fstype=~\"$diskfs\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))) by (device, instance, nodename, mountpoint)",
       "legendFormat": "disk available {{device}} {{nodename}} {{mountpoint}}"
      },
      {
       "expr": "round((sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\", fstype=~\"$diskfs\"}) by (device, instance, nodename, mountpoint) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\", fstype=~\"$diskfs\"}) by (device, instance, nodename, mountpoint)) / (sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\", fstype=~\"$diskfs\"}) by (device, instance, nodename, mountpoint) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\", fstype=~\"$diskfs\"}) by (device, instance, nodename, mountpoint) + sum(node_filesystem_avail_bytes{cluster=\"$cluster\", job=~\"$job\"}) by (device, instance, nodename, mountpoint)) * 100 * on(instance) group_left(nodename) (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))",
       "legendFormat": "disk utilization {{device}} {{nodename}} {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Utilization (Virtual Filesystems)",
     "type": "graph",
     "description": "The percentage of the virtual filesystems utilization is calculated using the fraction:\n```\n<space used>/(<space used> + <space free>)\n```\nThe value of <space free> is reduced by  5% of the available disk capacity, because   \nthe file system marks 5% of the available disk capacity as reserved. \nIf less than 5% is free, using the remaining reserved space requires root privileges.\nAny non-privileged users and processes are unable to write new data to the partition. See the list of explicitly ignored mount points and file systems at grafana level [here](https://github.com/dNationCloud/kubernetes-monitoring/blob/main/jsonnet/dashboards/grafana-templates.libsonnet) and at node-exporter level [here](https://github.com/dNationCloud/kubernetes-monitoring-stack/blob/main/chart/values.yaml)",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\", fstype!~\"$diskfs\"} * on(instance) group_left(nodename) (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))) by (device, instance, nodename)  - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\", fstype!~\"$diskfs\"} * on(instance) group_left(nodename) (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))) by (device, instance, nodename)",
       "legendFormat": "disk used {{device}} {{nodename}} {{mountpoint}}"
      },
      {
       "expr": "sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\", fstype!~\"$diskfs\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))) by (device, instance, nodename)",
       "legendFormat": "disk size {{device}} {{nodename}} {{mountpoint}}"
      },
      {
       "expr": "sum(node_filesystem_avail_bytes{cluster=\"$cluster\", job=~\"$job\", fstype!~\"$diskfs\"}\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))) by (device, instance, nodename)",
       "legendFormat": "disk available {{device}} {{nodename}} {{mountpoint}}"
      },
      {
       "expr": "round((sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\", fstype!~\"$diskfs\"}) by (device, instance, nodename) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\", fstype!~\"$diskfs\"}) by (device, instance, nodename)) / (sum(node_filesystem_size_bytes{cluster=\"$cluster\", job=~\"$job\", fstype!~\"$diskfs\"}) by (device, instance, nodename) - sum(node_filesystem_free_bytes{cluster=\"$cluster\", job=~\"$job\", fstype!~\"$diskfs\"}) by (device, instance, nodename) + sum(node_filesystem_avail_bytes{cluster=\"$cluster\", job=~\"$job\", fstype!~\"$diskfs\"}) by (device, instance, nodename)) * 100 * on(instance) group_left(nodename) (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename)))",
       "legendFormat": "disk utilization {{device}} {{nodename}} {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{cluster=\"$cluster\", job=~\"$job\"}[5m])) by (instance)\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))",
       "legendFormat": "read {{device}} {{nodename}}"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total{cluster=\"$cluster\", job=~\"$job\"}[5m])) by (instance)\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))",
       "legendFormat": "written {{device}} {{nodename}}"
      },
      {
       "expr": "sum(rate(node_disk_io_time_seconds_total{cluster=\"$cluster\", job=~\"$job\"}[5m])) by (instance)\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))",
       "legendFormat": "io time {{device}} {{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Transmit/Receive Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_errs_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m])\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))",
       "legendFormat": "Tx_{{device}} {{nodename}}"
      },
      {
       "expr": "rate(node_network_receive_errs_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m])\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))",
       "legendFormat": "Rx_{{device}} {{nodename}}"
      }
     ]
    },
    {
     "title": "Network Received",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m])\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))",
       "legendFormat": "{{device}} {{nodename}}"
      }
     ]
    },
    {
     "title": "Network Transmitted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{cluster=\"$cluster\", job=~\"$job\", device!~\"lo|veth.+|docker.+|flannel.+|cali.+|cbr.|cni.+|br.+\"}[5m])\n* on(instance) group_left(nodename) \n   (avg(node_uname_info{cluster=\"$cluster\", nodename=~\"$instance\"}) by (instance,nodename))",
       "legendFormat": "{{device}} {{nodename}}"
      }
     ]
    }
   ]
  }
 ]
}