{
 "title": "Container Detail",
 "tags": [
  "k8s",
  "container",
  "L3"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "datasource_logs", "label": "Logs datasource", "query": "loki" },
   { "name": "view", "label": "View by", "query": "pod,container" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_namespace_pod_container:container_memory_working_set_bytes, cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"$cluster\", node=~\"$instance\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"$cluster\", node=~\"$instance\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"$cluster\", node=~\"$instance\", namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   },
   { "name": "search", "label": "Logs Search" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container=~\"$container\"}) by ($view)",
     "legendFormat": "{{$view}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
     "legendFormat": "PodRequests - {{$view}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
     "legendFormat": "PodLimits - {{$view}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", id!=\"\", container=~\"$container\"}) by ($view)",
     "legendFormat": "{{$view}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
     "legendFormat": "PodRequests - {{$view}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by ($view)",
     "legendFormat": "PodLimits - {{$view}}"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Transmit/Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Tx_{{pod}}"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
       "legendFormat": "Rx_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Drops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transmit/Receive Drops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "Tx_{{pod}}"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "Rx_{{pod}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Count (avg for 10s intervals)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "logs" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |~ \"(?i)$search\"[10s])) by ($view)",
     "legendFormat": "{{$view}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |~ \"(?i)$search\""
    }
   ]
  }
 ]
}