{
 "title": "SSL Certificates",
 "tags": [
  "k8s",
  "app",
  "L1"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_uname_info, cluster)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ssl_probe_success{cluster=\"$cluster\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Unique Certificates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(max(ssl_cert_not_after{cluster=\"$cluster\", job=~\"$job\"}) by (issuer_cn, serial_no))"
    }
   ]
  },
  {
   "title": "Total Probe Targets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ssl_probe_success{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Expired/Failed Certificates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\n            (count(up{job=~\"$job\", cluster=\"$cluster\"}==0) OR on() vector(0))+\n            (count(ssl_probe_success{cluster=\"$cluster\"}==0) OR on() vector(0))+\n            (count((ssl_cert_not_after{cluster=\"$cluster\"}-time())<0) OR on() vector(0))+\n            (count((ssl_file_not_after{cluster=\"$cluster\"}-time())<0) OR on() vector(0))+\n            (count((ssl_kubeconfig_cert_not_after{cluster=\"$cluster\"}-time())<0) OR on()vector(0))+\n            (count((ssl_kubernetes_cert_not_after{cluster=\"$cluster\"}-time())<0) OR on()vector(0))\n            "
    }
   ]
  },
  {
   "title": "Certificates Nearing Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\n            (count(0<(ssl_cert_not_after{cluster=\"$cluster\"}-time())<8*24*60*60) OR on() vector(0))+\n            (count(0<(ssl_file_not_after{cluster=\"$cluster\"}-time())<8*24*60*60) OR on() vector(0))+\n            (count(0<(ssl_kubeconfig_cert_not_after{cluster=\"$cluster\"}-time())<8*24*60*60) OR on() vector(0)) +\n            (count(0<(ssl_kubernetes_cert_not_after{cluster=\"$cluster\"}-time())<8*24*60*60) OR on() vector(0))\n            "
    }
   ]
  },
  {
   "title": "Failed SSL Connects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Failed SSL Connects",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ssl_probe_success{cluster=\"$cluster\"}==0"
    }
   ]
  },
  {
   "title": "External SSL Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "External SSL Certificates",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ssl_cert_not_after{ job=~\"$job\", cluster=\"$cluster\" } - time()"
    }
   ]
  },
  {
   "title": "Kubeconfig Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Kubeconfig Certificates",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 40, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "ssl_kubeconfig_cert_not_after{ job=~\"$job\", cluster=\"$cluster\" } - time()"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal Kubernetes Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Internal Kubernetes Certificates",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 40, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "ssl_file_cert_not_after{ job=~\"$job\", cluster=\"$cluster\" }* on(pod) group_left(node) kube_pod_info{ cluster=\"$cluster\"} - time()"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Secret Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Kubernetes Secret Certificates",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 42, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "ssl_kubernetes_cert_not_after{ job=~\"$job\", cluster=\"$cluster\" } - time()"
      }
     ]
    }
   ]
  }
 ]
}