kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
    mode: wordpress-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.service_wordpress }}