apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-cluster-role-binding
subjects:
- kind: Group
  name: dev           # Name of the group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dev-cluster-role   # Name of the ClusterRole defined above
  apiGroup: rbac.authorization.k8s.io