apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding   #    Declares this resource as a ClusterRoleBinding
metadata:
  name: cluster-pod-reader-binding   #    The name of this ClusterRoleBinding
subjects:  #    Specifies the users, groups, or service accounts this ClusterRoleBinding applies to
- kind: User                  
  name: vishalk17   #    The name of the user being granted access
  apiGroup: rbac.authorization.k8s.io      
roleRef:   #    References the ClusterRole being bound by this ClusterRoleBinding
  kind: ClusterRole     
  name: cluster-pod-reader  #    The name of the ClusterRole being bound (must match the name of an existing ClusterRole)
  apiGroup: rbac.authorization.k8s.io 